# workflow ì˜ ì´ë¦„
name: Run Test

on:
  # develop ë¸Œëžœì¹˜ì— push ë‚˜ pull request ì´ë²¤íŠ¸ê°€ ì¼ì–´ë‚¬ì„ë•Œ í•´ë‹¹ workflow ë¥¼ trigger
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# workflowì˜ ì‹¤í–‰ì€ í•˜ë‚˜ ì´ìƒì˜ jobìœ¼ë¡œ êµ¬ì„± ë¨
jobs:
  # ì´ workflow ëŠ” "build" ë¼ëŠ” single job ìœ¼ë¡œ êµ¬ì„±
  build:
    # jobì´ ì‹¤í–‰ë  í™˜ê²½ - ìµœì‹  mac os
    runs-on: macos-12
    env:
      APIKEY: ${{ secrets.APIKEY }}
    steps:
    # uses í‚¤ì›Œë“œë¥¼ í†µí•´ Github Actionsì—ì„œ ê¸°ë³¸ìœ¼ë¡œ ì œê³µí•˜ëŠ” ì•¡ì…˜ì„ ì‚¬ìš© ê°€ëŠ¥. ì•„ëž˜ ì•¡ì…˜ì€ repository ì— ì²´í¬ì•„ì›ƒí•˜ëŠ” ê²ƒ
    - uses: actions/checkout@v3
    # shell ì´ìš©í•´ì„œ í•˜ë‚˜ì˜ command ìˆ˜í–‰
    - name: Test Xcode build ðŸ› 
      run: |
        echo -n $APIKEY | base64 --decode > Gom4ziz/Gom4ziz/Secret/APIKey.swift
        xcodebuild clean test -project Gom4ziz/Gom4ziz.xcodeproj -scheme Gom4zizTests -destination "platform=iOS Simulator,name=iPhone 13,OS=latest"
